import { PageView } from '@/config/routers/cr-plan/temp/@/layouts';
import { PageState } from '@/common/enums';
import permissionCrPlan from '@/config/routers/cr-plan/temp/snweb-module/es/_permissions/sm-cr-plan.js.js';

export default {
  path: 'cr-plan',
  name: 'cr-plan',
  component: PageView,
  meta: {
    title: '年月表管理',
    keepAlive: true,
    icon: 'calendar',
    permission: [permissionCrPlan.GroupName],
  },
  children: [
    {
      path: 'year-plan',
      name: 'year-plan',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/YearPlan'),
      meta: { title: '年表编制', keepAlive: false, permission: [permissionCrPlan.YearPlan.Default] },
      props: true,
    },
    {
      path: 'month-plan',
      name: 'month-plan',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/MonthPlan'),
      meta: { title: '月表编制', keepAlive: false, permission: [permissionCrPlan.MonthPlan.Default] },
      props: true,
    },
    {
      path: 'month-of-year-plan',
      name: 'month-of-year-plan',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/PlanMonthOfYear'),
      meta: { title: '年表月度计划', keepAlive: false, permission: [permissionCrPlan.MonthOfYearPlan.Default] },
      props: true,
    },

    {
      path: 'year-plan-records',
      name: 'year-plan-records',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/YearPlanRecords'),
      meta: { title: '年表记录', keepAlive: false, permission: [] },
      props: true,
    },
    {
      path: 'year-month-records',
      name: 'year-month-records',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/MonthPlanRecords'),
      meta: { title: '月表记录', keepAlive: false, permission: [] },
      props: true,
    },
    {
      path: 'vertical-skylight-plans',
      name: 'vertical-skylight-plans',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/VerticalSkylightPlans'),
      meta: { title: '垂直天窗计划', keepAlive: false, permission: [permissionCrPlan.SkylightPlan.Default] },
    },
    {
      path: 'skylight-plan-add/:organizationId/:planTime',
      name: 'skylight-plan-add',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/VerticalSkylightPlan'),
      hidden: true,
      meta: { title: '添加计划', keepAlive: false, permission: [permissionCrPlan.SkylightPlan.Create] },
      props: route => ({
        pageState: PageState.Add,
        organizationId: route.params.organizationId,
        planTime: route.params.planTime,
        planType: route.params.planType,
      }),
    },
    {
      path: 'skylight-plan-edit/:id/:organizationId/:planTime',
      name: 'skylight-plan-edit',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/VerticalSkylightPlan'),
      hidden: true,
      meta: { title: '编辑计划', keepAlive: false, permission: [permissionCrPlan.SkylightPlan.Update] },
      props: route => ({
        pageState: PageState.Edit,
        id: route.params.id,
        organizationId: route.params.organizationId,
        planTime: route.params.planTime,
        planType: route.params.planType,
        isChange:route.params.isChange,
      }),
    },
    {
      path: 'skylight-plan-view/:id/:organizationId',
      name: 'skylight-plan-view',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/VerticalSkylightPlan'),
      hidden: true,
      meta: { title: '查看计划', keepAlive: false, permission: permissionCrPlan.SkylightPlan.Detail },
      props: route => ({
        pageState: PageState.View,
        id: route.params.id,
        organizationId: route.params.organizationId,
        planTime: route.params.planTime,
        planType: route.params.planType,
      }),
    },

    {
      path: 'general-skylight-plans',
      name: 'general-skylight-plans',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/GeneralSkylightPlans'),
      meta: { title: '综合天窗计划', keepAlive: false, permission: [permissionCrPlan.SkylightPlan.Default] },
    },

    {
      path: 'out-of-skylight-plans',
      name: 'out-of-skylight-plans',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/OutOfSkylightPlans'),
      meta: { title: '天窗点外计划', keepAlive: false, permission: [permissionCrPlan.SkylightPlan.Default] },
    },

    {
      path: 'other-plans',
      name: 'other-plans',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/OtherPlans'),
      meta: { title: '其他计划', keepAlive: false, permission: [permissionCrPlan.OtherPlan.Default] },
    },
    {
      path: 'vertical-other-plan-add/:organizationId/:planTime',
      name: 'vertical-other-plan-add',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/OtherPlan'),
      hidden: true,
      meta: { title: '添加计划', keepAlive: false, permission: [permissionCrPlan.OtherPlan.Create] },
      props: route => ({
        pageState: PageState.Add,
        organizationId: route.params.organizationId,
        planTime: route.params.planTime,
      }),
    },
    {
      path: 'vertical-other-plan-edit/:id/:organizationId/:planTime',
      name: 'vertical-other-plan-edit',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/OtherPlan'),
      hidden: true,
      meta: { title: '编辑计划', keepAlive: false, permission: [permissionCrPlan.OtherPlan.Update] },
      props: route => ({
        pageState: PageState.Edit,
        id: route.params.id,
        organizationId: route.params.organizationId,
        planTime: route.params.planTime,
      }),
    },
    {
      path: 'vertical-other-plan-view/:id/:organizationId/:planTime',
      name: 'vertical-other-plan-view',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/OtherPlan'),
      hidden: true,
      meta: { title: '查看计划', keepAlive: false, permission: [permissionCrPlan.OtherPlan.Detail] },
      props: route => ({
        pageState: PageState.View,
        id: route.params.id,
        organizationId: route.params.organizationId,
        planTime: route.params.planTime,
      }),
    },

    {
      path: 'plan-changes',
      name: 'plan-changes',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/PlanChanges'),
      meta: { title: '未完成计划变更', keepAlive: false, permission: [permissionCrPlan.PlanChange.Default] },
    },
    {
      path: 'plan-change-add',
      name: 'plan-change-add',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/PlanChange'),
      hidden: true,
      meta: { title: '添加计划变更', keepAlive: false, permission: [permissionCrPlan.PlanChange.Create] },
      props: route => ({ pageState: PageState.Add, organizationId: route.params.organizationId }),
    },
    {
      path: 'plan-change-edit/:id/:organizationId',
      name: 'plan-change-edit',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/PlanChange'),
      hidden: true,
      meta: { title: '编辑计划变更', keepAlive: false, permission: [permissionCrPlan.PlanChange.Update] },
      props: route => ({ pageState: PageState.Edit, id: route.params.id, organizationId: route.params.organizationId }),
    },
    {
      path: 'plan-change-view/:id',
      name: 'plan-change-view',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/PlanChange'),
      hidden: true,
      meta: { title: '查看计划变更', keepAlive: false, permission: [permissionCrPlan.PlanChange.Detail] },
      props: route => ({ pageState: PageState.View, id: route.params.id }),
    },

    {
      path: 'year-month-change/:planType/:orgId/:orgName',
      name: 'year-month-change',
      hidden: true,
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/PlanYearMonthChange'),
      meta: {
        title: '年月表变更',
        keepAlive: false,
        permission: [permissionCrPlan.YearPlan.Alter, permissionCrPlan.MonthPlan.Alter],
      },
      props: route => ({ planType: route.params.planType, orgId: route.params.orgId, orgName: route.params.orgName }),
    },
    {
      path: 'plan-todos',
      name: 'plan-todos',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/PlanTodos'),
      meta: { title: '单位待办', keepAlive: false, permission: [permissionCrPlan.PlanTodo.Default] },
    },
    {
      path: 'sented-work-orders',
      name: 'sented-work-orders',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/SentedWorkOrders'),
      meta: { title: '已派工的', keepAlive: false, permission: [permissionCrPlan.SentedWorkOrders.Default] },
    },
    {
      path: 'sending-works',
      name: 'sending-works',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/SendingWorks'),
      meta: { title: '派工作业', keepAlive: false, permission: [permissionCrPlan.SendingWork.Default] },
    },
    {
      path: 'other-works',
      name: 'other-works',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/OtherWorks'),
      meta: { title: '其他作业', keepAlive: false, permission: [permissionCrPlan.OtherPlan.Default] },
    },
    {
      path: 'sending-works-finished',
      name: 'sending-works-finished',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/SendingWorksFinished'),
      meta: { title: '已完成的', keepAlive: false, permission: [permissionCrPlan.SendingWorksFinished.Default] },
    },
    {
      path: 'sending-work/:operatorType/:sendingWorkId',
      name: 'sending-work',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/SendingWork'),
      hidden: true,
      meta: { title: '派工作业单页', keepAlive: false, permission: [permissionCrPlan.SendingWork.Default] },
      props: route => ({
        operatorType: route.params.operatorType,
        id: route.params.id,
      }),
    },
    {
      path: 'maintenance-records',
      name: 'maintenance-records',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/MaintenanceRecords'),
      meta: { title: '检修记录', keepAlive: false, permission: [permissionCrPlan.MaintenanceRecord.Default] },
    },
    {
      path: 'maintenance-record-view/:organizationId/:repairGroupId',
      name: 'maintenance-record-view',
      component: () => import('@/config/routers/cr-plan/temp/@/views/cr-plan/MaintenanceRecord'),
      hidden: true,
      meta: {
        title: '查看设备检修记录',
        keepAlive: false,
        permission: [permissionCrPlan.MaintenanceRecord.Detail],
      },
      props: route => ({
        organizationId: route.params.organizationId,
        equipmentId: route.params.equipmentId,
        repairGroupId: route.params.repairGroupId,
        equipType: route.params.equipType,
        equipName: route.params.equipName,
        equipModelNumber: route.params.equipModelNumber,
        equipModelCode: route.params.equipModelCode,
        installationSite: route.params.installationSite,
      }),
    },
  ],
};
